/* confdefs.h */
#define PACKAGE_NAME "ios_webkit_debug_proxy"
#define PACKAGE_TARNAME "ios_webkit_debug_proxy"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "ios_webkit_debug_proxy 1.0"
#define PACKAGE_BUGREPORT "wrightt@google.com"
#define PACKAGE_URL ""
#define HAVE_LIBM 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_TIME_H 1
